In [1]:
import pandas as pd

In [5]:
df1 = pd.read_csv('distiluse_tSNE_hdbscan_0.01.csv')
df1['cluster'].value_counts()

cluster
1     14860
2      7058
0      4518
6      3871
3      3622
5      3329
9      3005
11     2937
8      2893
7      2570
4      2321
10      767
Name: count, dtype: int64

In [7]:
df1.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 51751 entries, 0 to 51750
Data columns (total 37 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   name_board         51751 non-null  object
 1   creator_thread     51565 non-null  object
 2   creator_id_thread  51751 non-null  int64
 3   name_thread        51751 non-null  object
 4   created_on         51751 non-null  object
 5   registration_date  50432 non-null  object
 6   total_posts        50432 non-null  float64
 7   reputation         50432 non-null  float64
 8   creator_post       51751 non-null  object
 9   creator_id_post    51751 non-null  int64
 10  content            51751 non-null  object
 11  created_on_post    51751 non-null  object
 12  cluster            51751 non-null  int64
 13  index              51751 non-null  int64
 14  size_percentage    51751 non-null  float64
 15  n_1_topics         51751 non-null  object
 16  n_2_topics         51751 non-null  object
 17  top_0              51751 non-null  object
 18  top_1              51751 non-null  object
 19  top_2              51751 non-null  object
 20  top_3              51751 non-null  object
 21  top_4              51751 non-null  object
 22  top_5              51751 non-null  object
 23  top_6              51751 non-null  object
 24  top_7              51751 non-null  object
 25  top_8              51751 non-null  object
 26  top_9              51751 non-null  object
 27  bottom_0           51751 non-null  object
 28  bottom_1           51751 non-null  object
 29  bottom_2           51751 non-null  object
 30  bottom_3           51751 non-null  object
 31  bottom_4           51751 non-null  object
 32  bottom_5           51751 non-null  object
 33  bottom_6           51751 non-null  object
 34  bottom_7           51751 non-null  object
 35  bottom_8           51751 non-null  object
 36  bottom_9           51751 non-null  object
dtypes: float64(3), int64(4), object(30)
memory usage: 14.6+ MB

In [8]:
df1[df1['cluster'] == 1][['name_thread', 'n_1_topics', 'n_2_topics']]

,name_thread,n_1_topics,n_2_topics
36891,Anyone seen heard MorpheusLabs Good USA mdma v...,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
36892,MDMA vendor germany Netherlands ship usa,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
36893,domestic vendor LSD,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
36894,US vendor Blue Punishers ww ship US,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
36895,vendor selling AMT,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
...,...,...,...
51746,Safe ground,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
51747,long long,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
51748,link CanadaHQ,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
51749,pgp Login,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."
51750,cannacreations Giveaway Update,"[('mdmadirtsharkresellers', 0.3637), ('ukdrugd...","[('morphine vendor', 0.4523), ('dutchxmdma ven..."